# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GorelPoc < Formula
  desc ""Testing the release pipeline""
  homepage "https://stenic.io"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/gorel-poc/releases/download/1.5.0/gorel-poc_darwin_amd64.tar.gz"
      sha256 "97dc20040b2f34bbfd7f734e28e304a4237ea080e704eb9ddbb18b17acfa7278"

      def install
        bin.install "gorel-poc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/gorel-poc/releases/download/1.5.0/gorel-poc_darwin_arm64.tar.gz"
      sha256 "67746361415e6f292e1b8e4fecb5cc48e5cf76bb624f0f16f19da39141c4e9a4"

      def install
        bin.install "gorel-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/gorel-poc/releases/download/1.5.0/gorel-poc_linux_arm64.tar.gz"
      sha256 "b91a67418bed340dc478ac39eaafd98388c399a6730b654a4f7076f83990c1ff"

      def install
        bin.install "gorel-poc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/gorel-poc/releases/download/1.5.0/gorel-poc_linux_armv6.tar.gz"
      sha256 "ef5605aa0a7fcf40d84d5315da74ff0edc4a00160f1ac0da9e391cc41aa294fe"

      def install
        bin.install "gorel-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/gorel-poc/releases/download/1.5.0/gorel-poc_linux_amd64.tar.gz"
      sha256 "6ea97bd1eb60d45a32a7d69cb3378784268802a35c6f460c125eb67ecd9b4b57"

      def install
        bin.install "gorel-poc"
      end
    end
  end

  test do
    system "#{bin}/gorel-poc -v"
  end
end
